config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "home" => "static_pages#index"
  devise_for :users
  resources :teachers, only: [:index,:show]

  namespace :admin do
    resources :departmentusers do
      collection { post :import }
    end
    resources :edit_topics
    resources :courses
    resources :trainings
    resources :labs
    resources :departments
    resources :subjects
    resources :students do
      collection { post :import }
    end
    resources :teachers do
      collection { post :import }
    end
    resources :spheres
    resources :admins
    resources  :admindepartments
    resources :topic_students do
      collection { post :import }
    end
    resources :books
    resources :reviews do
      collection { post :import }
    end
    resources :reports
    resources :councils
    resources :files
    resources :timenotifis
    resources :send_emails
    resources :time_protects
    get "overview" => "departments#tree"
    get "overviews" => "courses#tree"
    get "denghi" => "dispatchs#show", format: 'docx'
    get "xinthoi" => "dispatchs#cancel", format: 'docx'
    get "suadoi" => "dispatchs#edit", format: 'docx'
    get "dispatch" => "dispatchs#index"
    get "baove" => "dispatchs#protect_word", format: 'docx'
    get "baovebyexcel" => "dispatchs#protect_excel", format: 'xlsx'
    get "protect" => "dispatchs#protect"
    get "hoidong" => "dispatchs#councils", format: 'docx'
    get "hoidongbaove" => "dispatchs#indexcouncil"
    get "reportfile" => "reports#report"
    get "reportword/:id" => "reports#onereport", format: 'docx'
    get "example" => "reviews#example", format: 'xlsx'
    get "reported" => "dispatchs#reported",format: 'docx'
    get "indexreported" => "dispatchs#indexreported"
  end
  resources :edit_topics
  resources :alltopics
  resources :topics
  resources :updateinfors
  resources :teachers, only: [:show, :edit, :update]
  resources :students, only: [:show, :edit, :update]
  resources :department_users, only: [:show, :edit, :update]
  resources :admins, only: [:show, :edit, :update]
  resources :topic_teachers
  get "teachers/info/:id" => "alltopics#show"
  get "overview" => "admin/departments#tree"
  get "spheres" => "admin/spheres#index"
  get "teachers/search/detect" => "teachers#detect"

  post "info" => "ajax#update_info_status"
  get "get-info" => "ajax#get_info"
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :subjects
  has_many :departmentusers
  has_many :students
  has_many :teachers
  has_many :labs
  has_one :timenotifi
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_action :user_signin
  before_action :admin_department, only: [:edit, :update, :destroy, :new]
  before_action :find_department, only: [:show, :edit, :update, :destroy]
  def index
    @departments = Department.all
  end

  def show
  end

  def tree
    @departments = Department.paginate(page: params[:page],:per_page => 1)
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:success] = "Thêm khoa thành công"
      redirect_to admin_departments_path
    else
      flash[:danger] = "Thêm khoa thất bại"
      render :new
    end
  end

  def edit
  end

  def update
    if @department.update_attributes(department_params)
      flash[:success] = "Cập nhật khoa thành công"
      redirect_to admin_departments_path
    else
      flash[:danger] = "Cập nhật khoa thất bại"
      render :edit
    end
  end

  def destroy
    if @department.destroy
      flash[:success] = "Xóa khoa thành công"
      redirect_to admin_departments_path
    else
      flash[:danger] = "Xóa khoa thất bại"
      redirect_to admin_departments_path
    end
  end

  private
  def department_params
    params.require(:department).permit(:name, :office)
  end

  def find_department
    @department = Department.find_by(id: params[:id])
  end
end

app/views/admin/departments/edit.html.erb
<div class="clearfix"></div>
<h2><% provide(:title, "Sửa thông tin khoa ") %></h2>
<div class="x_content">
  <%= form_for [:admin, @department], :html => {class: "form-horizontal form-label-left"}  do |f| %>
    <div class="item form-group">
       <label class="control-label col-md-3 col-sm-3 col-xs-12" for="department_name">Tên khoa<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :name, :required => true, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <br>
    <div class="item form-group">
       <label class="control-label col-md-3 col-sm-3 col-xs-12" for="department_office">Văn phòng khoa<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :office, :required => true, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="ln_solid"></div>
      <div class="col-md-6 col-md-offset-3">
        <%= button_tag "Làm lại", type: :reset, class: "btn btn-primary" %>
        <%= f.submit "Sửa", class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/admin/departments/index.html.erb
<h2><% provide(:title, "Tất cả khoa") %></h2>
<div class="clearfix"></div>
<div class="x_content">
  <%= link_to "Tạo khoa", new_admin_department_path, class: "btn btn-primary" %>
  <div class="table-responsive">
      <table class="table table-striped jambo_table bulk_action">
          <thead>
              <tr class="headings">
                  <th>
                      <input type="checkbox" id="check-all" class="flat">
                  </th>
                  <th>Tên khoa</th>
                  <th>Văn phòng khoa</th>
                  <th class="column-title no-link last"><span class="nobr">Hành động</span>
                  </th>
                  <th class="bulk-actions" colspan="7">
                      <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                  </th>
              </tr>
          </thead>

          <tbody>
              <% @departments.each do |department| %>
                  <tr class="even pointer">
                      <td class="a-center ">
                          <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= department.name %></td>
                      <td class=" "><%= department.office %></td>
                      <td class=" last">
                          <%= link_to "Sửa", edit_admin_department_path(id: department.id) %>
                          |
                         <%= link_to "Xóa", [:admin, department], method: :delete,
                        data: {confirm: t("comfirm")} %>
                      </td>
                  </tr>
              <% end %>
          </tbody>
      </table>
  </div>
</div>

app/views/admin/departments/new.html.erb
<div class="clearfix"></div>
<h2><% provide(:title, "Thêm khoa mới ") %></h2>
<div class="x_content">
  <%= form_for [:admin, @department], :html => {class: "form-horizontal form-label-left"}  do |f| %>
    <div class="item form-group">
       <label class="control-label col-md-3 col-sm-3 col-xs-12" for="department_name">Tên khoa<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :name, :required => true, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <br>
    <div class="item form-group">
       <label class="control-label col-md-3 col-sm-3 col-xs-12" for="department_office">Văn phòng khoa<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :office, :required => true, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="ln_solid"></div>
      <div class="col-md-6 col-md-offset-3">
        <%= button_tag "Làm lại", type: :reset, class: "btn btn-primary" %>
        <%= f.submit "Thêm khoa", class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/admin/departments/show.html.erb
<h2><% provide(:title, "Thông tin khoa") %></h2>
<table class="table">
  <thead>
    <tr>
      <th>Tên khoa</th>
      <th>Văn phòng khoa</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @department.name %></td>
        <td><%= @department.office %></td>
        <td><%= link_to "Sửa", edit_admin_department_path(id: @department.id) %></td>
        <td><%= link_to "Xóa", [:admin, @department], method: :delete,
          data: {confirm: t("comfirm")} %></td>
      </tr>
  </tbody>
</table>

app/views/admin/departments/tree.html.erb
<h2><% provide(:title, "Cấu trúc cây khoa") %></h2>
<div class="clearfix"></div>
<div class="x_content">
  <% if current_user.rules < 3 %>
    <div style="margin-top: 15px; text-align: center;">
      <%= link_to "THÊM BỘ MÔN MỚI", new_admin_subject_path, class: "btn btn-primary" %>
      <%= link_to "THÊM PHÒNG THÍ NGHIỆM MỚI", new_admin_lab_path, class: "btn btn-primary" %>
    </div>
  <% elsif current_user.rules == 3 %>
    <%= render "layouts/menu_teacher" %>
  <% else %>
    <%= render "layouts/menu" %>
  <% end %>
  <div class="table-responsive">
      <table class="table table-striped jambo_table bulk_action">
          <thead>
              <tr class="headings">
                  <th>Khoa</th>
                  <th>Phân loại</th>
                  <th>Văn phòng khoa</th>
                  <% if current_user.rules < 3 %>
                    <th class="column-title no-link last"><span class="nobr">Hành động</span>
                  </th>
                  <% end %>
                  <th class="bulk-actions" colspan="7">
                      <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                  </th>
              </tr>
          </thead>

          <tbody>
              <% @departments.each do |department| %>
                  <tr class="even pointer">
                      <td class=" "><span class="fa fa-dot-circle-o"></span> <%= department.name %></td>
                      <td>Khoa</td>
                      <td class=" "><%= department.office %></td>
                      <% if current_user.rules < 3 %>
                        <td class=" last">
                          <%= link_to "Sửa", edit_admin_department_path(id: department.id) %>
                          |
                         <%= link_to "Xóa", [:admin, department], method: :delete,
                          data: {confirm: t("comfirm")} %>
                        </td>
                      <% end %>
                  </tr>
                  <% department.subjects.each do |subject|%>
                  <tr class="even pointer">
                        <td class=""><span style="margin-left:10px;" class="fa fa-arrow-right"></span> <%= subject.name %></td>
                        <td>Bộ môn</td>
                        <td></td>
                        <% if current_user.rules < 3 %>
                          <td class=" last">
                            <%= link_to "Sửa", edit_admin_subject_path(id: subject.id) %>
                            |
                           <%= link_to "Xóa", [:admin, subject], method: :delete,
                          data: {confirm: t("comfirm")} %>
                          </td>
                        <% end %>
                  </tr>
                  <% end %>
                  <% department.labs.each do |lab|%>
                  <tr class="even pointer">
                        <td><span style="margin-left:10px;" class="fa fa-arrow-right"></span> <%= lab.name %></td>
                        <td>Phòng thí nghiệm</td>
                        <td></td>
                        <% if current_user.rules < 3 %>
                          <td class=" last">
                            <%= link_to "Sửa", edit_admin_lab_path(id: lab.id) %>
                            |
                           <%= link_to "Xóa", [:admin, lab], method: :delete,
                          data: {confirm: t("comfirm")} %>
                          </td>
                        <% end %>
                  </tr>
                  <% end %>
              <% end %>
              <div style="text-align: center;">
                <%= will_paginate %>
              </div>
          </tbody>
      </table>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    <% if current_user.rules > 2 %>
      $('body').css("background-color", "#ffffff");
      $('.nav_menu').css("margin-top", "-10px");
      $('.table').css("width", "90%");
      $('.table').css("margin-left", "5%");
    <% end %>
  });
</script>