config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "home" => "static_pages#index"
  devise_for :users
  resources :teachers, only: [:index,:show]

  namespace :admin do
    resources :departmentusers do
      collection { post :import }
    end
    resources :edit_topics
    resources :courses
    resources :trainings
    resources :labs
    resources :departments
    resources :subjects
    resources :students do
      collection { post :import }
    end
    resources :teachers do
      collection { post :import }
    end
    resources :spheres
    resources :admins
    resources  :admindepartments
    resources :topic_students do
      collection { post :import }
    end
    resources :books
    resources :reviews do
      collection { post :import }
    end
    resources :reports
    resources :councils
    resources :files
    resources :timenotifis
    resources :send_emails
    resources :time_protects
    get "overview" => "departments#tree"
    get "overviews" => "courses#tree"
    get "denghi" => "dispatchs#show", format: 'docx'
    get "xinthoi" => "dispatchs#cancel", format: 'docx'
    get "suadoi" => "dispatchs#edit", format: 'docx'
    get "dispatch" => "dispatchs#index"
    get "baove" => "dispatchs#protect_word", format: 'docx'
    get "baovebyexcel" => "dispatchs#protect_excel", format: 'xlsx'
    get "protect" => "dispatchs#protect"
    get "hoidong" => "dispatchs#councils", format: 'docx'
    get "hoidongbaove" => "dispatchs#indexcouncil"
    get "reportfile" => "reports#report"
    get "reportword/:id" => "reports#onereport", format: 'docx'
    get "example" => "reviews#example", format: 'xlsx'
    get "reported" => "dispatchs#reported",format: 'docx'
    get "indexreported" => "dispatchs#indexreported"
  end
  resources :edit_topics
  resources :alltopics
  resources :topics
  resources :updateinfors
  resources :teachers, only: [:show, :edit, :update]
  resources :students, only: [:show, :edit, :update]
  resources :department_users, only: [:show, :edit, :update]
  resources :admins, only: [:show, :edit, :update]
  resources :topic_teachers
  get "teachers/info/:id" => "alltopics#show"
  get "overview" => "admin/departments#tree"
  get "spheres" => "admin/spheres#index"
  get "teachers/search/detect" => "teachers#detect"

  post "info" => "ajax#update_info_status"
  get "get-info" => "ajax#get_info"
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  belongs_to :department
  belongs_to :subject
  has_many :divisions
  has_many :researches
  has_many :reviews


  def self.import_teacher(teacher_hash)
    teacher_value = find_by(user_id: teacher_hash["user_id"]) || new
    teacher_value.attributes = teacher_hash.to_hash.slice(*teacher_hash.to_hash.keys)
    teacher_value.save
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < ApplicationController
  before_action :user_signin
  before_action :admin_department, only: [:new, :destroy]
  skip_before_action :verify_authenticity_token
  def index
    @users = User.where(rules: Settings.teacher_role)
    @subjects = Subject.where(department_id: current_user.departmentuser.department_id)
  end

  def show
  end

  def edit
    @user = User.find_by(id: params[:id])
    @teacher = Teacher.find_by(user_id: @user.id)
    @subject = Subject.find_by(id: @teacher.subject_id)
    @subjects = Subject.all
  end

  def update
    @user = User.find_by(id: params[:id])
    @teacher = Teacher.find_by(user_id: @user.id)
    if @user.update_attributes(first_name: params[:first_name],
     last_name: params[:last_name], code: params[:macanbo]) && @teacher.update_attributes(subject_id: params[:subject_id])
      flash[:success] = "Cập nhật thông tin thành công"
      redirect_to admin_students_path
    else
      flash[:danger] = "Cập nhật thông tin thất bại"
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @teacher = Teacher.find_by(user_id: @user.id)
    if @teacher.destroy && @user.destroy
      flash[:success] = "Xóa tài khoản thành công"
      redirect_to admin_teachers_path
    else
      flash[:danger] = "Xóa tài khoản thất bại"
      redirect_to admin_teachers_path
    end
  end

  def new
    @subjects = Subject.where(department_id: current_user.departmentuser.department_id)
  end

  def create
    total_id = []
    @user_id = User.new_teacher(params[:first_name], params[:last_name], params[:macanbo],
      params[:email], params[:description], params[:subject], current_user.departmentuser.department_id)
    total_id << @user_id
    User.delay.send_email_teacher(total_id)
    # User.find_by(id: @user_id).send_reset_password_instructions
    flash[:success] = "Thêm giáo viên thành công, hệ thống đang gửi email"
    redirect_to admin_teachers_path
  end


  def import
    total_id = User.import(params[:file], current_user.departmentuser.department_id)
    User.delay.send_email_teacher(total_id)
    redirect_to admin_teachers_path, notice: "Thêm thành công dữ liệu giảng viên, hệ thống đang gửi email"
  end

  private
  def teacher_params
    params.require(:course).permit(:name)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :user_signin
  def show
  end
  def edit
    @check = params[:check].to_i
    @user = User.find_by(id: params[:id])
    @teacher = Teacher.find_by(user_id: @user.id)
  end
  def update
    @user = User.find_by(id: params[:id])
    @teacher = Teacher.find_by(user_id: @user.id)
    if @user.update_attributes(first_name: params[:first_name],
     last_name: params[:last_name], birthday: params[:birthday],
     country: params[:country], province: params[:province], distric: params[:distric],
     town: params[:town]) && @teacher.update_attributes(description: params[:description])
      flash[:success] = "Cập nhật thành công"
      if params[:check].to_i == 1
        redirect_to new_updateinfor_path(check: 1)
      else

        redirect_to home_path(check: 1)
      end
    else
      render :edit
    end
  end

  def detect
  end

  #chua phan quyen
  def index
    @per_page = 3

    @data_teachers = Teacher.joins(:user,:department,:subject)
       .select('teachers.*,users.first_name,users.last_name,departments.id as department_id,departments.name as department_name,subjects.id as subject_id,subjects.name as subject_name')
       .where("subjects.department_id = departments.id")
    @page = 1
    start = @per_page * (@page - 1)
    if(@data_teachers.size % @per_page == 0)
      @total_page = (@data_teachers.size/@per_page)
    else
      @total_page = (@data_teachers.size/@per_page).round + 1
    end

    @teachers = @data_teachers.limit(@per_page).offset(start)

    @teachers.each do |item|
      @researches = Research.joins(:teacher).where("researches.teacher_id = ?",item.id)
      item.researches << @researches
    end

    @departments = Department.all
    if(params[:department_id])
      @arr = {}
      department_id = params[:department_id]
      @department = Department.find_by(id: department_id)

      @subject_belong_department = @department.subjects
      @arr.store("subjects",@subject_belong_department)

      @data_teachers = @data_teachers = Teacher.joins(:user,:department,:subject)
           .select('teachers.*,users.first_name,users.last_name,departments.id as department_id,departments.name as department_name,subjects.id as subject_id,subjects.name as subject_name')
      if(params[:param])
        if(params[:param].key?("research_id"))
          @research = Research.find_by(id: params[:param][:research_id])
          @data_teachers = @data_teachers.where("teachers.id = ?",@research.teacher_id)
        end
      end
      @data_teachers = @data_teachers.where("teachers.department_id = ?",department_id)

      start = @per_page * (@page - 1)
      if(@data_teachers.size % @per_page == 0)
        @total_page = (@data_teachers.size/@per_page)
      else
        @total_page = (@data_teachers.size/@per_page).round + 1
      end

      @teachers = @data_teachers.limit(@per_page).offset(start)

      s = ""
      @teachers.each_with_index do |item,index|
        @researches = Research.joins(:teacher).where("researches.teacher_id = ?",item.id)
        s << '<tr class="headings">'
        s <<  '<th class="column-title">' + (index + 1).to_s + '</th>'
        s <<  '<th class="column-title"><a href="/teachers/info/' + item.id.to_s + '">' + item.first_name.to_s + ' ' + item.last_name.to_s + '</a></th>'
        s <<  '<th class="column-title">Học vị </th>'
        s <<  '<th class="column-title">' + item.subject_name.to_s + ',' + item.department_name.to_s + '</th>'
        s <<  '<th class="column-title no-link last"><span class="nobr">'
            @researches.each do |item_research|
            s <<  '<p>' + item_research.name.to_s + '</p>'
            end
        s <<  '</span>'
        s <<  '</th>'
        s <<'</tr>'
      end
      @arr.store("teachers",s)
      @arr.store("total_page",@total_page)
      respond_to do |format|
        format.html
        format.text {render json: @arr}
      end
    end

    if(params[:subject_id])
      @arr = {}
      subject_id = params[:subject_id]
      @data_teachers = @teachers_department = Teacher.joins(:user,:department,:subject)
           .select('teachers.*,users.first_name,users.last_name,departments.id as department_id,departments.name as department_name,subjects.id as subject_id,subjects.name as subject_name')
      if(params[:param])
        if(params[:param].key?("department_id"))
          @data_teachers = @data_teachers.where("teachers.department_id = ?",params[:param][:department_id])
        end
        if(params[:param].key?("research_id"))
          @research = Research.find_by(id: params[:param][:research_id])
          @data_teachers = @data_teachers.where("teachers.id = ?", @research.teacher_id)
        end
      end
      @data_teachers = @data_teachers.where("teachers.subject_id = ?",subject_id)

      start = @per_page * (@page - 1)
      if(@data_teachers.size % @per_page == 0)
        @total_page = (@data_teachers.size/@per_page)
      else
        @total_page = (@data_teachers.size/@per_page).round + 1
      end

      @teachers = @data_teachers.limit(@per_page).offset(start)

      s = ""
      @teachers.each_with_index do |item,index|
        @researches = Research.joins(:teacher).where("researches.teacher_id = ?",item.id)
        s << '<tr class="headings">'
        s <<  '<th class="column-title">' + (index + 1).to_s + '</th>'
        s <<  '<th class="column-title"><a href="/teachers/info/' + item.id.to_s + '">' + item.first_name.to_s + ' ' + item.last_name.to_s + '</a></th>'
        s <<  '<th class="column-title">Học vị </th>'
        s <<  '<th class="column-title">' + item.subject_name.to_s + ',' + item.department_name.to_s + '</th>'
        s <<  '<th class="column-title no-link last"><span class="nobr">'
            @researches.each do |item_research|
            s <<  '<p>' + item_research.name.to_s + '</p>'
            end
        s <<  '</span>'
        s <<  '</th>'
        s <<'</tr>'
      end
      @arr.store("teachers",s)
      @arr.store("total_page",@total_page)
      respond_to do |format|
        format.html
        format.text {render json: @arr}
      end
    end

    @list_tree_spheres = show_tree_spheres()
    if(params[:sphere_id])
      @arr = {}
      sphere_id = params[:sphere_id]

      @research_belong_sphere = Research.find_by_sql ["select r.* from researches r join searchspheres s on r.id = s.research_id where s.sphere_id = ?",sphere_id]
      @arr.store("researches",@research_belong_sphere)

      respond_to do |format|
        format.html
        format.text {render json: @arr}
      end
    end

    if(params[:research_id])
      @arr = {}
      research_id = params[:research_id]

      @data_teachers = @teachers = Teacher.joins(:user,:department,:subject)
           .select('teachers.*,users.first_name,users.last_name,departments.id as department_id,departments.name as department_name,subjects.id as subject_id,subjects.name as subject_name')
      if(params[:param])
        if(params[:param].key?("department_id"))
          @data_teachers = @data_teachers.where("teachers.department_id = ?",params[:param][:department_id])
        end
        if(params[:param].key?("subject_id"))
          @data_teachers = @data_teachers.where("teachers.subject_id = ?",params[:param][:subject_id])
        end
      end
      @research = Research.find_by(id: research_id)
      @data_teachers = @data_teachers.where("teachers.id = ?",@research.teacher_id)

      start = @per_page * (@page - 1)
      if(@data_teachers.size % @per_page == 0)
        @total_page = (@data_teachers.size/@per_page)
      else
        @total_page = (@data_teachers.size/@per_page).round + 1
      end

      @teachers = @data_teachers.limit(@per_page).offset(start)

      s = ""
      @teachers.each_with_index do |item,index|
        @researches = Research.joins(:teacher).where("researches.teacher_id = ?",item.id)
        s << '<tr class="headings">'
        s <<  '<th class="column-title">' + (index + 1).to_s + '</th>'
        s <<  '<th class="column-title"><a href="/teachers/info/' + item.id.to_s + '">' + item.first_name.to_s + ' ' + item.last_name.to_s + '</a></th>'
        s <<  '<th class="column-title">Học vị </th>'
        s <<  '<th class="column-title">' + item.subject_name.to_s + ',' + item.department_name.to_s + '</th>'
        s <<  '<th class="column-title no-link last"><span class="nobr">'
            @researches.each do |item_research|
            s <<  '<p>' + item_research.name.to_s + '</p>'
            end
        s <<  '</span>'
        s <<  '</th>'
        s <<'</tr>'
      end
      @arr.store("teachers",s)
      @arr.store("total_page",@total_page)
      respond_to do |format|
        format.html
        format.text {render json: @arr}
      end
    end

    if(params[:query_string])
      @arr = {}
      query_string = params[:query_string]
      @data_teachers = Teacher.joins(:user,:department,:subject)
       .select('teachers.*,users.first_name,users.last_name,departments.id as department_id,departments.name as department_name,subjects.id as subject_id,subjects.name as subject_name')
      if(params[:param])
        if(params[:param].key?("department_id"))
          @data_teachers = @data_teachers.where("teachers.department_id = ?",params[:param][:department_id])
        end
        if(params[:param].key?("subject_id"))
          @data_teachers = @data_teachers.where("teachers.subject_id = ?",params[:param][:subject_id])
        end
        if(params[:param].key?("research_id"))
          @research = Research.find_by(id: params[:param][:research_id])
          @data_teachers = @data_teachers.where("teachers.id = ?",@research.teacher_id)
        end
      end
      if(params[:search_by] == 'name')
        @data_teachers = @data_teachers.where("users.first_name LIKE ?","%#{query_string}%")
        @teachers = @data_teachers
      elsif(params[:search_by] == 'research')

app/views/teachers/detect.html.erb
<style>
  #preview {
    padding: 20px;
  }
  #preview img {
    width: 100%;
    height: auto;
    overflow: hidden;
  }
</style>
<% if current_user.rules == 3 %>
    <%= render "layouts/menu_teacher" %>
  <% else %>
    <%= render "layouts/menu" %>
  <% end %>
<div class="col-xs-12">
  <div class="form-group">
    <label for="" class="col-xs-12 col-sm-6 col-sm-offset-2">Nhập link ảnh</label>
    <div class="col-xs-12 col-sm-6 col-sm-offset-2">
      <input class="form-control" type="text" id="img">
    </div>
    <div class="col-xs-12 col-sm-1">
      <button class="form-control" id="detect">Detect</button>
    </div>
    <div class="col-xs-12 col-sm-1">
      <button class="form-control" id="identify">Search</button>
    </div>
  </div>
</div>
<div class="col-xs-12 col-sm-6 col-sm-offset-3" id="preview">

</div>
<script>
  $(document).ready(function(){
    var faceId = '';
    $('#detect').click(function(){
      var src = $('#img').val();
      $('#preview').append('<img src="' + src + '">');
      $.ajax({
          url: "https://api.projectoxford.ai/face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=false&returnFaceAttributes=age",
          beforeSend: function(xhrObj){
              // Request headers
              xhrObj.setRequestHeader("Content-Type","application/json");
              xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key","373d34a194c64c738c6b7c712beaa7a8");
          },
          type: "POST",
          // Request body
          dataType: "json",
          data: '{"url": "' + src + '"}'
      })
      .done(function(data) {
        if(data.length > 0){
          console.log(data[0].faceId);
          faceId = data[0].faceId;
        } else {
          alert('Không nhận diện được ảnh');
          console.log('loi');
        }

      })
      .fail(function(error) {
          console.log(error);
      });
    });

    var personId = '';
    $('#identify').click(function(){
      $.when(
        $.ajax({
          url: "https://api.projectoxford.ai/face/v1.0/identify",
          beforeSend: function(xhrObj){
              // Request headers
              xhrObj.setRequestHeader("Content-Type","application/json");
              xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key","373d34a194c64c738c6b7c712beaa7a8");
          },
          type: "POST",
          // Request body
          dataType: "json",
          data: '{"personGroupId":"uet","faceIds":["' + faceId + '",],"maxNumOfCandidatesReturned":1,"confidenceThreshold": 0.7}'
        })
        .done(function(data) {
          if(data.length > 0){
            alert("success");
            personId = data[0].candidates[0].personId;
          } else {
            alert('Không nhận diện được ảnh');
          }
        })
        .fail(function(error) {
            console.log(error);
        })
      ).then(function(){
        $.ajax({
          url: "https://api.projectoxford.ai/face/v1.0/persongroups/uet/persons/" + personId,
          beforeSend: function(xhrObj){
              // Request headers
              xhrObj.setRequestHeader("Content-Type","application/json");
              xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key","373d34a194c64c738c6b7c712beaa7a8");
          },
          type: "GET",
          // Request body
          dataType: "json",
          data: '{}'
        })
        .done(function(data) {
          alert(data.userData);
          console.log(data);
            console.log(data.userData);
        })
        .fail(function(error) {
            console.log(error);
        });
      });
    });
  });
</script>

app/views/teachers/edit.html.erb
<style>
body {
  background: #ffffff;
}
</style>
<div class="x_content">
  <%= form_tag({controller: "teachers", action: "update"}, method: "put", class: "form-horizontal form-label-left") do %>
    <input type="hidden" name="check" value="<%= @check %>">
    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first_name">Họ <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="first_name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="first_name" placeholder="" required="required" type="text" value="<%=@user.first_name %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last_name">Tên <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="last_name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="last_name" placeholder="" required="required" type="text" value="<%= @user.last_name %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="birthday">Ngày sinh
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="birthday" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="birthday" placeholder="" type="date" value="<%= @user.birthday %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="country">Quốc tịch
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="country" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="country" placeholder="" type="text" value="<%= @user.country %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="province">Tỉnh/Thành phố
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="province" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="province" placeholder="" type="text" value="<%= @user.province %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="distric">Quận/Huyện
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="distric" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="distric" placeholder="" type="text" value="<%= @user.distric %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="town">Phường/Thị xã
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="town" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="town" placeholder="" type="text" value="<%= @user.town %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Mô tả
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="description" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="description" placeholder="" type="text" value="<%= @teacher.description %>">
      </div>
    </div>

    <div class="ln_solid"></div>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
          <button id="send" type="submit" class="btn btn-success" name="submit">Cập nhật</button>
        <button type="reset" class="btn btn-primary">Làm lại</button>
      </div>
    </div>
  <% end %>
</div>

app/views/teachers/show.html.erb
<style>
body {
  background: #ffffff;
}
.edit {
  width: 80%;
  margin-top: 20px;
}

.ava {
  width: 80%;
  margin-top: 5px;
}
table {
  table-layout: fixed;
}
tr td:last-child{
    width:60%;
    white-space:nowrap;
}
</style>
<div class="row">
  <div class="col-md-3 col-lg-3">
    <%= image_tag current_user.avatar.url, id: "img" %>
    <%= link_to "Sửa thông tin", edit_teacher_path(current_user.id), class: "btn btn-primary edit" %>
    <%= link_to "Thay avatar", edit_user_registration_path, class: "btn btn-success ava" %>
     <%= link_to "Thêm hướng nghiên cứu", new_updateinfor_path, class: "btn btn-warning ava" %>
  </div>
  <div class=" col-md-9 col-lg-9 ">
    <table class="table table-user-information">
      <tbody>
        <tr>
          <td>Họ</td>
          <td><%= current_user.first_name %></td>
        </tr>
        <tr>
          <td>Tên</td>
          <td><%= current_user.last_name %></td>
        </tr>
        <tr>
          <td>Ngày sinh</td>
          <td><%= current_user.birthday %></td>
        </tr>

           <tr>
               <tr>
          <td>Quốc tịch </td>
          <td><%= current_user.country %></td>
        </tr>
          <tr>
          <td>Tỉnh/Thành phố</td>
          <td><%= current_user.province %></td>
        </tr>
        <tr>
          <td>Phường/Thị xã </td>
          <td><%= current_user.distric %></td>
        </tr>
          <td>Khoa</td>
          <td><%= current_user.teacher.department.name %>
          </td>

        </tr>

      </tbody>
    </table>
  </div>
</div>