config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "home" => "static_pages#index"
  devise_for :users
  resources :teachers, only: [:index,:show]

  namespace :admin do
    resources :departmentusers do
      collection { post :import }
    end
    resources :edit_topics
    resources :courses
    resources :trainings
    resources :labs
    resources :departments
    resources :subjects
    resources :students do
      collection { post :import }
    end
    resources :teachers do
      collection { post :import }
    end
    resources :spheres
    resources :admins
    resources  :admindepartments
    resources :topic_students do
      collection { post :import }
    end
    resources :books
    resources :reviews do
      collection { post :import }
    end
    resources :reports
    resources :councils
    resources :files
    resources :timenotifis
    resources :send_emails
    resources :time_protects
    get "overview" => "departments#tree"
    get "overviews" => "courses#tree"
    get "denghi" => "dispatchs#show", format: 'docx'
    get "xinthoi" => "dispatchs#cancel", format: 'docx'
    get "suadoi" => "dispatchs#edit", format: 'docx'
    get "dispatch" => "dispatchs#index"
    get "baove" => "dispatchs#protect_word", format: 'docx'
    get "baovebyexcel" => "dispatchs#protect_excel", format: 'xlsx'
    get "protect" => "dispatchs#protect"
    get "hoidong" => "dispatchs#councils", format: 'docx'
    get "hoidongbaove" => "dispatchs#indexcouncil"
    get "reportfile" => "reports#report"
    get "reportword/:id" => "reports#onereport", format: 'docx'
    get "example" => "reviews#example", format: 'xlsx'
    get "reported" => "dispatchs#reported",format: 'docx'
    get "indexreported" => "dispatchs#indexreported"
  end
  resources :edit_topics
  resources :alltopics
  resources :topics
  resources :updateinfors
  resources :teachers, only: [:show, :edit, :update]
  resources :students, only: [:show, :edit, :update]
  resources :department_users, only: [:show, :edit, :update]
  resources :admins, only: [:show, :edit, :update]
  resources :topic_teachers
  get "teachers/info/:id" => "alltopics#show"
  get "overview" => "admin/departments#tree"
  get "spheres" => "admin/spheres#index"
  get "teachers/search/detect" => "teachers#detect"

  post "info" => "ajax#update_info_status"
  get "get-info" => "ajax#get_info"
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :students
  belongs_to :course
end

app/controllers/admin/trainings_controller.rb
class Admin::TrainingsController < ApplicationController
  before_action :user_signin
  before_action :find_training, only: [:show, :edit, :update, :destroy]
  def index
    @trainings = Training.all
  end

  def show
  end

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      flash[:success] = "Thêm chương trình đào tạo thành công"
      redirect_to admin_trainings_path
    else
      flash[:danger] = "Thêm chương trình đào tạo thất bại"
      render :new
    end
  end

  def edit
  end

  def update
    if @training.update_attributes(training_params)
      flash[:success] = "Cập nhật chương trình đào tạo thành công"
      redirect_to admin_trainings_path
    else
      flash[:danger] = "Cập nhật chương trình đào tạo thất bại"
      render :edit
    end
  end

  def destroy
    if @training.destroy
      flash[:success] = "Xóa chương trình đào tạo thành công"
      redirect_to admin_trainings_path
    else
      flash[:danger] = "Xóa chương trình đào tạo thất bại"
      redirect_to admin_trainings_path
    end
  end

  private
  def training_params
    params.require(:training).permit(:name, :description, :course_id)
  end

  def find_training
    @training = Training.find_by(id: params[:id])
  end
end

app/views/admin/trainings/edit.html.erb
<div class="clearfix"></div>
<h2><% provide(:title, "Sửa Chương trình đào tạo") %></h2>
<div class="x_content">
  <%= form_for [:admin, @training], :html => {class: "form-horizontal form-label-left"} do |f| %>
    <div class="item form-group">
       <label class="control-label col-md-3 col-sm-3 col-xs-12" for="training_name">Tên chương trình<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :name, :required => true, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <br>
    <div class="clearfix"></div>
    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="training_description">Mô tả</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :description, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <br>
    <div class="clearfix"></div>
    <div class="item form-group">
     <label class="control-label col-md-3 col-sm-3 col-xs-12">Khóa học<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.collection_select :course_id, Course.all, :id, :name, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="ln_solid"></div>
    <div class="col-md-6 col-md-offset-3">
      <%= button_tag "Làm lại", type: :reset, class: "btn btn-primary" %>
      <%= f.submit "Sửa chương trình", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/trainings/index.html.erb
<h2><% provide(:title, "Tất cả Chương trình đào tạo") %></h2>
<div class="clearfix"></div>
<div class="x_content">
  <div class="table-responsive">
      <table class="table table-striped jambo_table bulk_action">
          <thead>
              <tr class="headings">
                  <th>
                      <input type="checkbox" id="check-all" class="flat">
                  </th>
                  <th>Tên chương trình</th>
                  <th>Mô tả</th>
                  <th>Khóa học</th>
                  <th class="column-title no-link last"><span class="nobr">Hành động</span>
                  </th>
                  <th class="bulk-actions" colspan="7">
                      <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                  </th>
              </tr>
          </thead>

          <tbody>
              <% @trainings.each do |training| %>
                  <tr class="even pointer">
                      <td class="a-center ">
                          <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=""><%= training.name %></td>
                      <td class=""><%= training.description %></td>
                      <td class=""><%= training.course.name %></td>
                      <td class=" last">
                          <%= link_to "Sửa", edit_admin_training_path(id: training.id) %>
                          |
                         <%= link_to "Xóa", [:admin, training], method: :delete,
                          data: {confirm: t("comfirm")} %>
                      </td>
                  </tr>
              <% end %>
          </tbody>
      </table>
  </div>
</div>

app/views/admin/trainings/new.html.erb
<div class="clearfix"></div>
<h2><% provide(:title, "Chương trình đào tạo mới") %></h2>
<div class="x_content">
  <%= form_for [:admin, @training], :html => {class: "form-horizontal form-label-left"} do |f| %>
    <div class="item form-group">
       <label class="control-label col-md-3 col-sm-3 col-xs-12" for="training_name">Tên chương trình<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :name, :required => true, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <br>
    <div class="clearfix"></div>
    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="training_description">Mô tả</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :description, class: "form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <br>
    <div class="clearfix"></div>
    <div class="item form-group">
     <label class="control-label col-md-3 col-sm-3 col-xs-12">Khóa học<span class="required">*</span></label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.collection_select :course_id, Course.all, :id, :name, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="ln_solid"></div>
    <div class="col-md-6 col-md-offset-3">
      <%= button_tag "Làm lại", type: :reset, class: "btn btn-primary" %>
      <%= f.submit "Thêm chương trình", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/trainings/show.html.erb
<h2>Training</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Course</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @training.name %></td>
        <td><%= @training.description %></td>
        <td><%= @training.course.name %></td>
        <td><%= link_to "edit", edit_admin_training_path(id: training.id) %></td>
        <td><%= link_to "delete", [:admin, @training], method: :delete,
          data: {confirm: t("comfirm")} %></td>
      </tr>
  </tbody>
</table>