config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "home" => "static_pages#index"
  devise_for :users
  resources :teachers, only: [:index,:show]

  namespace :admin do
    resources :departmentusers do
      collection { post :import }
    end
    resources :edit_topics
    resources :courses
    resources :trainings
    resources :labs
    resources :departments
    resources :subjects
    resources :students do
      collection { post :import }
    end
    resources :teachers do
      collection { post :import }
    end
    resources :spheres
    resources :admins
    resources  :admindepartments
    resources :topic_students do
      collection { post :import }
    end
    resources :books
    resources :reviews do
      collection { post :import }
    end
    resources :reports
    resources :councils
    resources :files
    resources :timenotifis
    resources :send_emails
    resources :time_protects
    get "overview" => "departments#tree"
    get "overviews" => "courses#tree"
    get "denghi" => "dispatchs#show", format: 'docx'
    get "xinthoi" => "dispatchs#cancel", format: 'docx'
    get "suadoi" => "dispatchs#edit", format: 'docx'
    get "dispatch" => "dispatchs#index"
    get "baove" => "dispatchs#protect_word", format: 'docx'
    get "baovebyexcel" => "dispatchs#protect_excel", format: 'xlsx'
    get "protect" => "dispatchs#protect"
    get "hoidong" => "dispatchs#councils", format: 'docx'
    get "hoidongbaove" => "dispatchs#indexcouncil"
    get "reportfile" => "reports#report"
    get "reportword/:id" => "reports#onereport", format: 'docx'
    get "example" => "reviews#example", format: 'xlsx'
    get "reported" => "dispatchs#reported",format: 'docx'
    get "indexreported" => "dispatchs#indexreported"
  end
  resources :edit_topics
  resources :alltopics
  resources :topics
  resources :updateinfors
  resources :teachers, only: [:show, :edit, :update]
  resources :students, only: [:show, :edit, :update]
  resources :department_users, only: [:show, :edit, :update]
  resources :admins, only: [:show, :edit, :update]
  resources :topic_teachers
  get "teachers/info/:id" => "alltopics#show"
  get "overview" => "admin/departments#tree"
  get "spheres" => "admin/spheres#index"
  get "teachers/search/detect" => "teachers#detect"

  post "info" => "ajax#update_info_status"
  get "get-info" => "ajax#get_info"
end

app/controllers/admin/admindepartments_controller.rb
class Admin::AdmindepartmentsController < ApplicationController
  before_action :user_signin
  skip_before_action :verify_authenticity_token
  before_action :admin

  def index
    @users = User.where(rules: Settings.department_role)
  end

  def new
  end

  def create
    @password = rand(100000..999999)
    User.create(first_name: params[:first_name],last_name: params[:last_name],code: params[:macanbo],
      email: params[:email], rules: Settings.department_role, password: @password)
    @id = User.find_by(code: params[:macanbo])
    if @id
      flash[:success] = "Tạo tài khoản admin thành công"
      Departmentuser.create(job_title: params[:job_title], user_id: @id.id)
      User.find_by(id: @id.id).send_reset_password_instructions
    else
      flash[:danger] = "Tạo tài khoản thất bại"
    end
    redirect_to admin_admindepartments_path
  end

  def edit
    @user = User.find_by(id: params[:id])
    @admin = Departmentuser.find_by(user_id: @user.id)
  end

  def update
    @user = User.find_by(id: params[:id])
    @admin = Departmentuser.find_by(user_id: @user.id)
    if @user.update_attributes(first_name: params[:first_name],
     last_name: params[:last_name], birthday: params[:birthday],
     country: params[:country], province: params[:province], distric: params[:distric],
     town: params[:town]) && @admin.update_attributes(job_title: params[:job_title])
      flash[:success] = "Cập nhật thông tin thành công"
      redirect_to admin_admindepartments_path
    else
      flash[:danger] = "Cập nhật thông tin thất bại"
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @admin = Departmentuser.find_by(user_id: @user.id)
    if @admin.destroy && @user.destroy
      redirect_to admin_admindepartments_path
    else
      redirect_to admin_admindepartments_path
    end
  end
end

app/views/admin/admindepartments/_new.html.erb
<style>
  .check {
    color: red;
  }
</style>
<div class="x_content" style="margin-top: 40px">

  <form class="form-horizontal form-label-left form" method="POST" action="/admin/admindepartments" method="post" accept-charset="utf-8">

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="firs_tname">Mã cán bộ <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="macanbo" class="form-control col-md-7 col-xs-12 required" data-validate-length-range="6" data-validate-words="2" name="macanbo" type="text" placeholder="102304">
        <span class="check"></span>
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first_name">Họ <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="first_name" class="form-control col-md-7 col-xs-12 required" data-validate-length-range="6" data-validate-words="2" name="first_name" type="text">
        <span class="check"></span>
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last_name">Tên <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="last_name" class="form-control col-md-7 col-xs-12 required" data-validate-length-range="6" data-validate-words="2" name="last_name" type="text">
        <span class="check"></span>
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input type="email" id="email" name="email" placeholder="abc@gmail.com" class="form-control col-md-7 col-xs-12 required">
        <span class="check"></span>
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="job_title">Chức vụ <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input type="text" id="job_title" name="job_title" placeholder="Mô tả" class="form-control col-md-7 col-xs-12 required">
        <span class="check"></span>
      </div>
    </div>
    <div class="ln_solid"></div>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
          <button type="reset" class="btn btn-primary" name="reset">Làm lại</button>
        <button id="send" type="submit" class="btn btn-success">Tạo tài khoản</button>
      </div>
    </div>
  </form>
</div>
<script type="text/javascript">
$(".form").submit(function(){
    var isFormValid = true;
    $(".required").each(function(){
        if ($.trim($(this).val()).length == 0){
            $(this).next().text("Thông tin không được để trống")
            isFormValid = false;
        } else {
            $(this).next().text("");
        }
    });
    return isFormValid;
});
</script>

app/views/admin/admindepartments/_table.html.erb
<div class="x_content" style="margin-top: 40px">
  <div class="table-responsive">
    <table class="table table-striped jambo_table bulk_action">
      <thead>
        <tr class="headings">
          <th>
            <input type="checkbox" id="check-all" class="flat">
          </th>
          <th class="column-title">STT </th>
          <th class="column-title">Họ </th>
          <th class="column-title">Tên </th>
          <th class="column-title">Ngày sinh </th>
          <th class="column-title">Chức vụ </th>
          <th class="column-title">Giới tính </th>
          <th class="column-title">Địa chỉ </th>
          <th class="column-title">Email </th>
          <th class="column-title">Mã cán bộ </th>
          <th class="column-title">Ghi chú </th>

          <th class="column-title no-link last"><span class="nobr">Hành động</span>
          </th>
          <th class="bulk-actions" colspan="7">
            <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @users.each_with_index do |item,index| %>
          <tr class="even pointer">
            <td class="a-center ">
              <input type="checkbox" class="flat" name="table_records">
            </td>
            <td class=" "><%= index + 1 %></td>
            <td class=" "><a href=""> <%= item.first_name %></a></td>
            <td class=" "><a href=""> <%= item.last_name %></a></td>
            <td class=" "><a href=""> <%= item.birthday %></a></td>
            <td class=" "><a href=""> Quản lý</a></td>
            <td class=" "><a href=""> <%= item.genner %></a></td>
            <td class=" "><a href=""> <%= item.province %></a></td>
            <td class=" "><a href=""> <%= item.email %></a></td>
            <td class=" "><a href=""> <%= item.code %></a></td>
            <% if item.teacher %>
              <td class=" "><%= item.teacher.description %></td>
            <% else %>
              <td class=" "></td>
            <% end %>
            <td class=" last">
              <%= link_to "Sửa", edit_admin_admindepartment_path(id: item.id) %>
               |
               <% if current_user.id != item.id %>
                <%= link_to "Xóa", admin_admindepartment_path(item.id), method: :delete,
                  data: {confirm: t("comfirm")} %>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/admindepartments/edit.html.erb
<h2><% provide(:title, "Sửa tài khoản admin") %></h2>
<div class="x_content">
  <%= form_tag({controller: "admin/admindepartments", action: "update"}, method: "put", class: "form-horizontal form-label-left") do %>
    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first_name">Họ <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="first_name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="first_name" placeholder="" required="required" type="text" value="<%=@user.first_name %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last_name">Tên <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="last_name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="last_name" placeholder="" required="required" type="text" value="<%= @user.last_name %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="birthday">Ngày sinh <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="birthday" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="birthday" placeholder="" required="required" type="date" value="<%= @user.birthday %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="country">Quốc tịch <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="country" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="country" placeholder="" required="required" type="text" value="<%= @user.country %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="province">Tỉnh/Thành phố <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="province" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="province" placeholder="" required="required" type="text" value="<%= @user.province %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="distric">Quận/Huyện <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="distric" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="distric" placeholder="" required="required" type="text" value="<%= @user.distric %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="town">Phường/Thị xã <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="town" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="town" placeholder="" required="required" type="text" value="<%= @user.town %>">
      </div>
    </div>

    <div class="item form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="job_title">Chức vụ <span class="required">*</span>
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <input id="job_title" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="job_title" placeholder="" required="required" type="text" value="<%= @admin.job_title %>">
      </div>
    </div>

    <div class="ln_solid"></div>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
          <button id="send" type="submit" class="btn btn-success" name="submit">Cập nhật</button>
        <button type="reset" class="btn btn-primary">Làm lại</button>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/admindepartments/index.html.erb
<h2><% provide(:title, "Quản lý tài khoản khoa") %></h2>
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#home" role="tab" data-toggle="tab">DANH SÁCH TÀI KHOẢN</a></li>
  <li><a href="#profile" role="tab" data-toggle="tab">THÊM TÀI KHOẢN KHOA</a></li>
  <li><a href="#settings" role="tab" data-toggle="tab">TÀI LIÊỤ, HƯỚNG DẪN</a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="home">
        <%= render "table" %>
    </div>
    <div class="tab-pane" id="profile">
        <%= render "new" %>
    </div>
    <div class="tab-pane" id="settings">
        DOCUMENT
    </div>
</div>